// This file is automatically generated by qtc from "about.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line about.qtpl:1
package templates

//line about.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line about.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line about.qtpl:2
type AboutPage struct {
	BasePage
}

//line about.qtpl:7
func (page *AboutPage) StreamGetBody(qw422016 *qt422016.Writer) {
	//line about.qtpl:7
	qw422016.N().S(`
  <div class="container-fluid" id="sbexr-about-data">
      <h4>What is this?</h4>

      <p>
        You are looking at a <b>code browser</b> for <b>`)
	//line about.qtpl:12
	qw422016.E().S(page.Project)
	//line about.qtpl:12
	qw422016.N().S(`</b>.
      </p>

      <p>
        By using this web interface, you can navigate the source code of <b>`)
	//line about.qtpl:16
	qw422016.E().S(page.Project)
	//line about.qtpl:16
	qw422016.N().S(`</b> by <b>following simple links</b>, <b>search it</b> by using the box in the navigation bar, or use <b>vi inspired</b> key bindings to move within files.
      </p>

      <p>
        It should all be pretty intuitive, but to get started, here are a few things you may want to try:
        <ul>
          <li>Search for files or symbols by using <b>'f'</b>, <b>'s'</b> or the pull down menu to the left of the search box.</li>
          <li>Press <b>'?'</b> to have a help screen with key bindings, and <b>'a'</b> or <b>ESC</b> to <b>hide this screen</b>.</li>
          <li>Try to drag variables or functions to get more details about them.</li>
        </ul>
      </p>

      <p>
        This site was generated via <a href="https://www.github.com/ccontavalli/sbexr"><b>sbexr</b></a>, which uses <a href="http://llvm.org">LLVM</a> and <a href="http://clang.llvm.org">clang</a> to parse and index the code.
      </p>

      <p>
        <b>sbexr</b> is free software (as in "free speech"), <a href="https://www.github.com/ccontavalli/sbexr">under heavy development</a>. <a href="http://sbexr.rabexc.org">sbexr.rabexc.org</a> and the Linux kernel source code are used as a playground to test new features, observe bugs, and gather feedback. Check there often if you want to see new features in action.
      </p>

      <p>
        As of today, the best way to know more about the project or participate in the development is to <a href="https://groups.google.com/forum/#!forum/sbexr/join">join the mailing list</a>,
        and follow the project on <a href="https://www.github.com/ccontavalli/sbexr">github</a>.
      </p>

  </div>
`)
//line about.qtpl:42
}

//line about.qtpl:42
func (page *AboutPage) WriteGetBody(qq422016 qtio422016.Writer) {
	//line about.qtpl:42
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line about.qtpl:42
	page.StreamGetBody(qw422016)
	//line about.qtpl:42
	qt422016.ReleaseWriter(qw422016)
//line about.qtpl:42
}

//line about.qtpl:42
func (page *AboutPage) GetBody() string {
	//line about.qtpl:42
	qb422016 := qt422016.AcquireByteBuffer()
	//line about.qtpl:42
	page.WriteGetBody(qb422016)
	//line about.qtpl:42
	qs422016 := string(qb422016.B)
	//line about.qtpl:42
	qt422016.ReleaseByteBuffer(qb422016)
	//line about.qtpl:42
	return qs422016
//line about.qtpl:42
}
