// This file is automatically generated by qtc from "base.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line base.qtpl:1
package templates

//line base.qtpl:1
import "github.com/ccontavalli/sbexr/server/structs"

//line base.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line base.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line base.qtpl:4
type Page interface {
	//line base.qtpl:4
	GetBody() string
	//line base.qtpl:4
	StreamGetBody(qw422016 *qt422016.Writer)
	//line base.qtpl:4
	WriteGetBody(qq422016 qtio422016.Writer)
	//line base.qtpl:4
	GetTitle() string
	//line base.qtpl:4
	StreamGetTitle(qw422016 *qt422016.Writer)
	//line base.qtpl:4
	WriteGetTitle(qq422016 qtio422016.Writer)
	//line base.qtpl:4
	GetPath() string
	//line base.qtpl:4
	StreamGetPath(qw422016 *qt422016.Writer)
	//line base.qtpl:4
	WriteGetPath(qq422016 qtio422016.Writer)
//line base.qtpl:4
}

//line base.qtpl:12
func StreamPageTemplate(qw422016 *qt422016.Writer, page Page) {
	//line base.qtpl:12
	qw422016.N().S(`<!DOCTYPE html><html lang='en'><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><title>`)
	//line base.qtpl:20
	page.StreamGetTitle(qw422016)
	//line base.qtpl:20
	qw422016.N().S(`</title>`)
	//line base.qtpl:21
	StreamAddCss(qw422016)
	//line base.qtpl:21
	qw422016.N().S(`</head><body><div class="container-fluid">`)
	//line base.qtpl:27
	StreamAddNavBar(qw422016, page)
	//line base.qtpl:28
	StreamAddFastJs(qw422016)
	//line base.qtpl:28
	qw422016.N().S(`</div><div class="container-fluid">`)
	//line base.qtpl:32
	page.StreamGetBody(qw422016)
	//line base.qtpl:32
	qw422016.N().S(`</div>`)
	//line base.qtpl:35
	StreamAddSlowJs(qw422016)
	//line base.qtpl:35
	qw422016.N().S(`</body></html>`)
//line base.qtpl:38
}

//line base.qtpl:38
func WritePageTemplate(qq422016 qtio422016.Writer, page Page) {
	//line base.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line base.qtpl:38
	StreamPageTemplate(qw422016, page)
	//line base.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line base.qtpl:38
}

//line base.qtpl:38
func PageTemplate(page Page) string {
	//line base.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
	//line base.qtpl:38
	WritePageTemplate(qb422016, page)
	//line base.qtpl:38
	qs422016 := string(qb422016.B)
	//line base.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
	//line base.qtpl:38
	return qs422016
//line base.qtpl:38
}

//line base.qtpl:40
type BasePage structs.JNavData

//line base.qtpl:42
func (page *BasePage) StreamGetBody(qw422016 *qt422016.Writer) {
	//line base.qtpl:42
	qw422016.N().S(`NO BODY`)
//line base.qtpl:42
}

//line base.qtpl:42
func (page *BasePage) WriteGetBody(qq422016 qtio422016.Writer) {
	//line base.qtpl:42
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line base.qtpl:42
	page.StreamGetBody(qw422016)
	//line base.qtpl:42
	qt422016.ReleaseWriter(qw422016)
//line base.qtpl:42
}

//line base.qtpl:42
func (page *BasePage) GetBody() string {
	//line base.qtpl:42
	qb422016 := qt422016.AcquireByteBuffer()
	//line base.qtpl:42
	page.WriteGetBody(qb422016)
	//line base.qtpl:42
	qs422016 := string(qb422016.B)
	//line base.qtpl:42
	qt422016.ReleaseByteBuffer(qb422016)
	//line base.qtpl:42
	return qs422016
//line base.qtpl:42
}

//line base.qtpl:44
func (page *BasePage) StreamGetPath(qw422016 *qt422016.Writer) {
//line base.qtpl:44
}

//line base.qtpl:44
func (page *BasePage) WriteGetPath(qq422016 qtio422016.Writer) {
	//line base.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line base.qtpl:44
	page.StreamGetPath(qw422016)
	//line base.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line base.qtpl:44
}

//line base.qtpl:44
func (page *BasePage) GetPath() string {
	//line base.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
	//line base.qtpl:44
	page.WriteGetPath(qb422016)
	//line base.qtpl:44
	qs422016 := string(qb422016.B)
	//line base.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
	//line base.qtpl:44
	return qs422016
//line base.qtpl:44
}

//line base.qtpl:46
func StreamGetParentsPath(qw422016 *qt422016.Writer, data *structs.JNavData) {
	//line base.qtpl:47
	for _, parent := range data.Parents {
		//line base.qtpl:47
		qw422016.N().S(`<a href="`)
		//line base.qtpl:48
		qw422016.E().S(parent.Href)
		//line base.qtpl:48
		qw422016.N().S(`">`)
		//line base.qtpl:48
		qw422016.E().S(parent.Name)
		//line base.qtpl:48
		qw422016.N().S(`</a>/`)
		//line base.qtpl:49
	}
	//line base.qtpl:50
	qw422016.E().S(data.Name)
//line base.qtpl:51
}

//line base.qtpl:51
func WriteGetParentsPath(qq422016 qtio422016.Writer, data *structs.JNavData) {
	//line base.qtpl:51
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line base.qtpl:51
	StreamGetParentsPath(qw422016, data)
	//line base.qtpl:51
	qt422016.ReleaseWriter(qw422016)
//line base.qtpl:51
}

//line base.qtpl:51
func GetParentsPath(data *structs.JNavData) string {
	//line base.qtpl:51
	qb422016 := qt422016.AcquireByteBuffer()
	//line base.qtpl:51
	WriteGetParentsPath(qb422016, data)
	//line base.qtpl:51
	qs422016 := string(qb422016.B)
	//line base.qtpl:51
	qt422016.ReleaseByteBuffer(qb422016)
	//line base.qtpl:51
	return qs422016
//line base.qtpl:51
}

//line base.qtpl:53
func StreamGetJnavTitle(qw422016 *qt422016.Writer, data *structs.JNavData) {
	//line base.qtpl:53
	if data.Project != "" {
		//line base.qtpl:53
		qw422016.E().S(data.Project)
		//line base.qtpl:53
		qw422016.N().S(` `)
		//line base.qtpl:53
	}
	//line base.qtpl:53
	if data.Tag != "" {
		//line base.qtpl:53
		qw422016.E().S(data.Tag)
		//line base.qtpl:53
		qw422016.N().S(` `)
		//line base.qtpl:53
	}
	//line base.qtpl:53
	if (data.Tag != "" || data.Project != "") && (data.Name != "" || data.Path != "") {
		//line base.qtpl:53
		qw422016.N().S(`-`)
		//line base.qtpl:53
		qw422016.N().S(` `)
		//line base.qtpl:53
	}
	//line base.qtpl:53
	if data.Path != "" {
		//line base.qtpl:53
		qw422016.E().S(data.Path)
		//line base.qtpl:53
	} else if data.Name != "" {
		//line base.qtpl:53
		qw422016.E().S(data.Name)
		//line base.qtpl:53
	}
//line base.qtpl:53
}

//line base.qtpl:53
func WriteGetJnavTitle(qq422016 qtio422016.Writer, data *structs.JNavData) {
	//line base.qtpl:53
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line base.qtpl:53
	StreamGetJnavTitle(qw422016, data)
	//line base.qtpl:53
	qt422016.ReleaseWriter(qw422016)
//line base.qtpl:53
}

//line base.qtpl:53
func GetJnavTitle(data *structs.JNavData) string {
	//line base.qtpl:53
	qb422016 := qt422016.AcquireByteBuffer()
	//line base.qtpl:53
	WriteGetJnavTitle(qb422016, data)
	//line base.qtpl:53
	qs422016 := string(qb422016.B)
	//line base.qtpl:53
	qt422016.ReleaseByteBuffer(qb422016)
	//line base.qtpl:53
	return qs422016
//line base.qtpl:53
}

//line base.qtpl:55
func (page *BasePage) StreamGetTitle(qw422016 *qt422016.Writer) {
	//line base.qtpl:56
	StreamGetJnavTitle(qw422016, (*structs.JNavData)(page))
//line base.qtpl:57
}

//line base.qtpl:57
func (page *BasePage) WriteGetTitle(qq422016 qtio422016.Writer) {
	//line base.qtpl:57
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line base.qtpl:57
	page.StreamGetTitle(qw422016)
	//line base.qtpl:57
	qt422016.ReleaseWriter(qw422016)
//line base.qtpl:57
}

//line base.qtpl:57
func (page *BasePage) GetTitle() string {
	//line base.qtpl:57
	qb422016 := qt422016.AcquireByteBuffer()
	//line base.qtpl:57
	page.WriteGetTitle(qb422016)
	//line base.qtpl:57
	qs422016 := string(qb422016.B)
	//line base.qtpl:57
	qt422016.ReleaseByteBuffer(qb422016)
	//line base.qtpl:57
	return qs422016
//line base.qtpl:57
}
