// This file is automatically generated by qtc from "css.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line css.qtpl:2
package templates

//line css.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line css.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line css.qtpl:2
func StreamAddCss(qw422016 *qt422016.Writer) {
	//line css.qtpl:2
	qw422016.N().S(`<link href="../../../static/bootstrap/css/bootstrap.min.css" rel="stylesheet"><link href="../../../static/bootstrap/css/dropdowns-enhancement.min.css" rel="stylesheet"><link href="../../../static/animated-modal/animate.min.css" rel="stylesheet"><link href="../../../static/font-awesome/css/font-awesome.min.css" rel="stylesheet"><link href="../../../static/style.css" rel="stylesheet">`)
//line css.qtpl:8
}

//line css.qtpl:8
func WriteAddCss(qq422016 qtio422016.Writer) {
	//line css.qtpl:8
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line css.qtpl:8
	StreamAddCss(qw422016)
	//line css.qtpl:8
	qt422016.ReleaseWriter(qw422016)
//line css.qtpl:8
}

//line css.qtpl:8
func AddCss() string {
	//line css.qtpl:8
	qb422016 := qt422016.AcquireByteBuffer()
	//line css.qtpl:8
	WriteAddCss(qb422016)
	//line css.qtpl:8
	qs422016 := string(qb422016.B)
	//line css.qtpl:8
	qt422016.ReleaseByteBuffer(qb422016)
	//line css.qtpl:8
	return qs422016
//line css.qtpl:8
}
