// This file is automatically generated by qtc from "directory.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line directory.qtpl:1
package templates

//line directory.qtpl:1
import "github.com/ccontavalli/sbexr/server/structs"

//line directory.qtpl:2
import "github.com/dustin/go-humanize"

//line directory.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line directory.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line directory.qtpl:5
type DirectoryPage struct {
	structs.JDir
	Index []byte
}

//line directory.qtpl:11
func (page *DirectoryPage) StreamGetPath(qw422016 *qt422016.Writer) {
	//line directory.qtpl:11
	StreamGetParentsPath(qw422016, &page.JDir.JNavData)
//line directory.qtpl:11
}

//line directory.qtpl:11
func (page *DirectoryPage) WriteGetPath(qq422016 qtio422016.Writer) {
	//line directory.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line directory.qtpl:11
	page.StreamGetPath(qw422016)
	//line directory.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line directory.qtpl:11
}

//line directory.qtpl:11
func (page *DirectoryPage) GetPath() string {
	//line directory.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
	//line directory.qtpl:11
	page.WriteGetPath(qb422016)
	//line directory.qtpl:11
	qs422016 := string(qb422016.B)
	//line directory.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
	//line directory.qtpl:11
	return qs422016
//line directory.qtpl:11
}

//line directory.qtpl:12
func (page *DirectoryPage) StreamGetTitle(qw422016 *qt422016.Writer) {
	//line directory.qtpl:12
	StreamGetJnavTitle(qw422016, &page.JDir.JNavData)
//line directory.qtpl:12
}

//line directory.qtpl:12
func (page *DirectoryPage) WriteGetTitle(qq422016 qtio422016.Writer) {
	//line directory.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line directory.qtpl:12
	page.StreamGetTitle(qw422016)
	//line directory.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line directory.qtpl:12
}

//line directory.qtpl:12
func (page *DirectoryPage) GetTitle() string {
	//line directory.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
	//line directory.qtpl:12
	page.WriteGetTitle(qb422016)
	//line directory.qtpl:12
	qs422016 := string(qb422016.B)
	//line directory.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
	//line directory.qtpl:12
	return qs422016
//line directory.qtpl:12
}

//line directory.qtpl:13
func (page *DirectoryPage) StreamGetBody(qw422016 *qt422016.Writer) {
	//line directory.qtpl:13
	qw422016.N().S(`
<div class="row">

<div class="col-md-4">
<table class="table table-hover table-condensed">
`)
	//line directory.qtpl:18
	if len(page.Dirs) > 0 {
		//line directory.qtpl:18
		qw422016.N().S(`
  <tr>
    <th colspan="2">Directory</th>
    <th>Files</th>
  </tr>
  `)
		//line directory.qtpl:23
		for _, dir := range page.Dirs {
			//line directory.qtpl:23
			qw422016.N().S(`
  <tr>
    <td width="20"><i class="glyphicon glyphicon-folder-open"></i></td>
    <td><a href="`)
			//line directory.qtpl:26
			qw422016.E().S(dir.Href)
			//line directory.qtpl:26
			qw422016.N().S(`">`)
			//line directory.qtpl:26
			qw422016.E().S(dir.Name)
			//line directory.qtpl:26
			qw422016.N().S(`</a></td>
    <td>`)
			//line directory.qtpl:27
			qw422016.N().D(dir.Size)
			//line directory.qtpl:27
			qw422016.N().S(`</td>
  </tr>
  `)
			//line directory.qtpl:29
		}
		//line directory.qtpl:29
		qw422016.N().S(`
  `)
		//line directory.qtpl:30
		if len(page.Files) > 0 {
			//line directory.qtpl:30
			qw422016.N().S(`
  <tr>
    <td colspan="3"></td>
  </tr>
  `)
			//line directory.qtpl:34
		}
		//line directory.qtpl:34
		qw422016.N().S(`
`)
		//line directory.qtpl:35
	}
	//line directory.qtpl:35
	qw422016.N().S(`

`)
	//line directory.qtpl:37
	if len(page.Files) > 0 {
		//line directory.qtpl:37
		qw422016.N().S(`
  <tr>
    <th colspan="2">File</th>
    <th>Size</th>
  </tr>
  `)
		//line directory.qtpl:42
		for _, file := range page.Files {
			//line directory.qtpl:42
			qw422016.N().S(`
  <tr>
    <td width="20">
      `)
			//line directory.qtpl:45
			switch file.Type {
			//line directory.qtpl:46
			case "parsed":
				//line directory.qtpl:46
				qw422016.N().S(`<i title="Code - parsed & indexed" class="fa fa-code"></i>
        `)
			//line directory.qtpl:47
			case "blob":
				//line directory.qtpl:47
				qw422016.N().S(`<i title="Binary blob - ignored" class="fa fa-ban"></i>
        `)
			//line directory.qtpl:48
			case "text":
				//line directory.qtpl:48
				qw422016.N().S(`<i title="Text data - indexed" class="fa fa-file-text-o"></i>
        `)
			//line directory.qtpl:49
			default:
				//line directory.qtpl:49
				qw422016.N().S(`<i title="Media - download only" class="fa fa-download"></i>
      `)
				//line directory.qtpl:50
			}
			//line directory.qtpl:50
			qw422016.N().S(`
    </td>
    <td><a href="`)
			//line directory.qtpl:52
			qw422016.E().S(file.Href)
			//line directory.qtpl:52
			qw422016.N().S(`">`)
			//line directory.qtpl:52
			qw422016.E().S(file.Name)
			//line directory.qtpl:52
			qw422016.N().S(`</a></td>
    <td>`)
			//line directory.qtpl:53
			qw422016.N().S(humanize.Bytes(uint64(file.Size)))
			//line directory.qtpl:53
			qw422016.N().S(`</td>
  </tr>
  `)
			//line directory.qtpl:55
		}
		//line directory.qtpl:55
		qw422016.N().S(`
`)
		//line directory.qtpl:56
	}
	//line directory.qtpl:56
	qw422016.N().S(`
</table>
</div>

`)
	//line directory.qtpl:60
	if len(page.Index) > 0 {
		//line directory.qtpl:60
		qw422016.N().S(`
<div class="col-md-8">
<h2>`)
		//line directory.qtpl:62
		qw422016.E().S(page.Project)
		//line directory.qtpl:62
		qw422016.N().S(` `)
		//line directory.qtpl:62
		qw422016.E().S(page.Tag)
		//line directory.qtpl:62
		qw422016.N().S(` - `)
		//line directory.qtpl:62
		qw422016.E().S(page.Name)
		//line directory.qtpl:62
		qw422016.N().S(`</h2>
<pre class='code'><span id='line-number'></span>`)
		//line directory.qtpl:63
		qw422016.N().Z(page.Index)
		//line directory.qtpl:63
		qw422016.N().S(`<span class='cl'></span></pre>
</div>
`)
		//line directory.qtpl:65
	}
	//line directory.qtpl:65
	qw422016.N().S(`

</div>
</div>
`)
//line directory.qtpl:69
}

//line directory.qtpl:69
func (page *DirectoryPage) WriteGetBody(qq422016 qtio422016.Writer) {
	//line directory.qtpl:69
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line directory.qtpl:69
	page.StreamGetBody(qw422016)
	//line directory.qtpl:69
	qt422016.ReleaseWriter(qw422016)
//line directory.qtpl:69
}

//line directory.qtpl:69
func (page *DirectoryPage) GetBody() string {
	//line directory.qtpl:69
	qb422016 := qt422016.AcquireByteBuffer()
	//line directory.qtpl:69
	page.WriteGetBody(qb422016)
	//line directory.qtpl:69
	qs422016 := string(qb422016.B)
	//line directory.qtpl:69
	qt422016.ReleaseByteBuffer(qb422016)
	//line directory.qtpl:69
	return qs422016
//line directory.qtpl:69
}
