// This file is automatically generated by qtc from "javascript.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line javascript.qtpl:2
package templates

//line javascript.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line javascript.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line javascript.qtpl:2
func StreamAddFastJs(qw422016 *qt422016.Writer) {
	//line javascript.qtpl:2
	qw422016.N().S(`<script src="../../sources/meta/globals.js"></script><script src="../../optional.js"></script><script src="../../../static/jquery.min.js"></script><script src="../../../static/bootstrap/js/bootstrap.min.js"></script><script src="../../../static/bootstrap/js/dropdowns-enhancement.js"></script><script src="../../../static/animated-modal/animatedModal.js"></script><script src="../../../static/jquery.autocomplete.js"></script><script src="../../../static/js.cookie.js"></script><script src="../../../static/local.js"></script>`)
//line javascript.qtpl:12
}

//line javascript.qtpl:12
func WriteAddFastJs(qq422016 qtio422016.Writer) {
	//line javascript.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line javascript.qtpl:12
	StreamAddFastJs(qw422016)
	//line javascript.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line javascript.qtpl:12
}

//line javascript.qtpl:12
func AddFastJs() string {
	//line javascript.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
	//line javascript.qtpl:12
	WriteAddFastJs(qb422016)
	//line javascript.qtpl:12
	qs422016 := string(qb422016.B)
	//line javascript.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
	//line javascript.qtpl:12
	return qs422016
//line javascript.qtpl:12
}

//line javascript.qtpl:14
func StreamAddSlowJs(qw422016 *qt422016.Writer) {
	//line javascript.qtpl:14
	qw422016.N().S(`<script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');ga('create', 'UA-40501108-2', 'auto');ga('send', 'pageview');</script>`)
//line javascript.qtpl:24
}

//line javascript.qtpl:24
func WriteAddSlowJs(qq422016 qtio422016.Writer) {
	//line javascript.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line javascript.qtpl:24
	StreamAddSlowJs(qw422016)
	//line javascript.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line javascript.qtpl:24
}

//line javascript.qtpl:24
func AddSlowJs() string {
	//line javascript.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
	//line javascript.qtpl:24
	WriteAddSlowJs(qb422016)
	//line javascript.qtpl:24
	qs422016 := string(qb422016.B)
	//line javascript.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
	//line javascript.qtpl:24
	return qs422016
//line javascript.qtpl:24
}
