// This file is automatically generated by qtc from "navbar.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line navbar.qtpl:1
package templates

//line navbar.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line navbar.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line navbar.qtpl:1
func StreamAddNavBar(qw422016 *qt422016.Writer, page Page) {
	//line navbar.qtpl:1
	qw422016.N().S(`
<div class="container">
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid" id="navbar">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>

      <span class="navbar-brand" style="padding-top: 8px">
        <a href="../meta/index.html"><i class="glyphicon glyphicon-hdd" style="vertical-align: middle"></i></a>&nbsp;/`)
	//line navbar.qtpl:16
	page.StreamGetPath(qw422016)
	//line navbar.qtpl:16
	qw422016.N().S(`
      </span>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <!-- mostly taken from http://www.bootply.com/t7O3HSGlbc -->
    <div class="collapse navbar-collapse" id="main-navbar">
        <div class="form-group" style="margin-top: 8px; margin-bottom: 0px;">
          <div class="input-group">

          <div class="input-group-btn">
            <button class="btn btn-default correct-height" data-label-placement><i class="glyphicon glyphicon-console data-label"></i></button>
            <button data-toggle="dropdown" class="btn btn-default dropdown-toggle correct-height"><span class="caret"></span> </button>
            <ul class="dropdown-menu">
              <li>
                <input type="radio" id="sb-symbol" name="sb" value="symbol" checked>
                <label for="sb-symbol"><i class="glyphicon glyphicon-console data-label"></i> Symbol</label>
              </li>
              <li>
                <input type="radio" id="sb-file" name="sb" value="file">
                <label for="sb-file"><i class="glyphicon glyphicon-file data-label"></i> File</label>
              </li>
              <li>
                <input type="radio" id="sb-text" name="sb" value="text">
                <label for="sb-text"><i class="glyphicon glyphicon-text-background data-label"></i> Text</label>
              </li>
              <li>
                <input type="radio" id="sb-line" name="sb" value="line">
                <label for="sb-line"><i class="glyphicon glyphicon-indent-left data-label"></i> Line</label>
              </li>
            </ul>
          </div>

            <input type="text" name="search" id="searchbox-symbol" class="form-control" placeholder="Search symbol (std::list, list, kfree_skb, any full or partial variable/class/function/... name)">
            <input type="text" name="search" id="searchbox-file" class="form-control hidden" placeholder="Search file (/usr/include/alloca.h, alloca.h, any full or partial path)">
            <input type="text" name="search" id="searchbox-text" class="form-control hidden" placeholder="Search text (content of comments, strings, full text search over the source code)">
            <input type="text" name="search" id="searchbox-line" class="form-control hidden" placeholder="Go to line (53, 1120, just type the line number and enter)">

        <div class="input-group-btn">
          <div class="btn-group hidden" id="tag-menu">
            <button data-toggle="dropdown" class="btn btn-default dropdown-toggle" id="tag-default"></button>
            <ul class="dropdown-menu pull-center" id="tag-entries">
            </ul>
          </div>

          <a class="btn btn-default" href="../meta/about.html" type="button" id="sbexr-about"><i title="About this site" class="glyphicon glyphicon-info-sign"></i></a>
          <a class="btn btn-default" href="../meta/help.html" type="button" id="sbexr-help"><i title="Help!!" class="glyphicon glyphicon-question-sign"></i></a>
        </div>

          </div>
        </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>
`)
//line navbar.qtpl:71
}

//line navbar.qtpl:71
func WriteAddNavBar(qq422016 qtio422016.Writer, page Page) {
	//line navbar.qtpl:71
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line navbar.qtpl:71
	StreamAddNavBar(qw422016, page)
	//line navbar.qtpl:71
	qt422016.ReleaseWriter(qw422016)
//line navbar.qtpl:71
}

//line navbar.qtpl:71
func AddNavBar(page Page) string {
	//line navbar.qtpl:71
	qb422016 := qt422016.AcquireByteBuffer()
	//line navbar.qtpl:71
	WriteAddNavBar(qb422016, page)
	//line navbar.qtpl:71
	qs422016 := string(qb422016.B)
	//line navbar.qtpl:71
	qt422016.ReleaseByteBuffer(qb422016)
	//line navbar.qtpl:71
	return qs422016
//line navbar.qtpl:71
}
