// This file is automatically generated by qtc from "source.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line source.qtpl:1
package templates

//line source.qtpl:1
import "github.com/ccontavalli/sbexr/server/structs"

//line source.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line source.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line source.qtpl:4
type SourcePage struct {
	structs.JDir
	Content []byte
}

//line source.qtpl:10
func (page *SourcePage) StreamGetPath(qw422016 *qt422016.Writer) {
	//line source.qtpl:10
	StreamGetParentsPath(qw422016, &page.JDir.JNavData)
//line source.qtpl:10
}

//line source.qtpl:10
func (page *SourcePage) WriteGetPath(qq422016 qtio422016.Writer) {
	//line source.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line source.qtpl:10
	page.StreamGetPath(qw422016)
	//line source.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line source.qtpl:10
}

//line source.qtpl:10
func (page *SourcePage) GetPath() string {
	//line source.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
	//line source.qtpl:10
	page.WriteGetPath(qb422016)
	//line source.qtpl:10
	qs422016 := string(qb422016.B)
	//line source.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
	//line source.qtpl:10
	return qs422016
//line source.qtpl:10
}

//line source.qtpl:11
func (page *SourcePage) StreamGetTitle(qw422016 *qt422016.Writer) {
	//line source.qtpl:11
	StreamGetJnavTitle(qw422016, &page.JDir.JNavData)
//line source.qtpl:11
}

//line source.qtpl:11
func (page *SourcePage) WriteGetTitle(qq422016 qtio422016.Writer) {
	//line source.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line source.qtpl:11
	page.StreamGetTitle(qw422016)
	//line source.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line source.qtpl:11
}

//line source.qtpl:11
func (page *SourcePage) GetTitle() string {
	//line source.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
	//line source.qtpl:11
	page.WriteGetTitle(qb422016)
	//line source.qtpl:11
	qs422016 := string(qb422016.B)
	//line source.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
	//line source.qtpl:11
	return qs422016
//line source.qtpl:11
}

//line source.qtpl:12
func (page *SourcePage) StreamGetBody(qw422016 *qt422016.Writer) {
	//line source.qtpl:12
	qw422016.N().S(`<pre class='code'><span id='line-number'></span>`)
	//line source.qtpl:12
	qw422016.N().Z(page.Content)
	//line source.qtpl:12
	qw422016.N().S(`<span class='cl'></span></pre>`)
//line source.qtpl:12
}

//line source.qtpl:12
func (page *SourcePage) WriteGetBody(qq422016 qtio422016.Writer) {
	//line source.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line source.qtpl:12
	page.StreamGetBody(qw422016)
	//line source.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line source.qtpl:12
}

//line source.qtpl:12
func (page *SourcePage) GetBody() string {
	//line source.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
	//line source.qtpl:12
	page.WriteGetBody(qb422016)
	//line source.qtpl:12
	qs422016 := string(qb422016.B)
	//line source.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
	//line source.qtpl:12
	return qs422016
//line source.qtpl:12
}
