// This file is automatically generated by qtc from "symbol.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line symbol.qtpl:1
package templates

//line symbol.qtpl:1
import "github.com/ccontavalli/sbexr/server/structs"

//line symbol.qtpl:2
import "strings"

//line symbol.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line symbol.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line symbol.qtpl:4
type SymbolPage struct {
	BasePage
	Symbol *structs.SymbolObject
}

//line symbol.qtpl:11
func StreamGetHumanLinkage(qw422016 *qt422016.Writer, value int) {
	//line symbol.qtpl:12
	switch value {
	//line symbol.qtpl:13
	case 1:
		//line symbol.qtpl:13
		qw422016.N().S(`local`)
	//line symbol.qtpl:15
	case 2:
		//line symbol.qtpl:15
		qw422016.N().S(`local`)
	//line symbol.qtpl:17
	case 3:
		//line symbol.qtpl:17
		qw422016.N().S(`global`)
	//line symbol.qtpl:19
	case 4:
		//line symbol.qtpl:19
		qw422016.N().S(`global`)
	//line symbol.qtpl:21
	default:
		//line symbol.qtpl:22
	}
//line symbol.qtpl:23
}

//line symbol.qtpl:23
func WriteGetHumanLinkage(qq422016 qtio422016.Writer, value int) {
	//line symbol.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line symbol.qtpl:23
	StreamGetHumanLinkage(qw422016, value)
	//line symbol.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line symbol.qtpl:23
}

//line symbol.qtpl:23
func GetHumanLinkage(value int) string {
	//line symbol.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
	//line symbol.qtpl:23
	WriteGetHumanLinkage(qb422016, value)
	//line symbol.qtpl:23
	qs422016 := string(qb422016.B)
	//line symbol.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
	//line symbol.qtpl:23
	return qs422016
//line symbol.qtpl:23
}

//line symbol.qtpl:27
func StreamGetHumanAccess(qw422016 *qt422016.Writer, value int) {
	//line symbol.qtpl:28
	switch value {
	//line symbol.qtpl:29
	case 0:
		//line symbol.qtpl:29
		qw422016.N().S(`public`)
	//line symbol.qtpl:31
	case 1:
		//line symbol.qtpl:31
		qw422016.N().S(`protected`)
	//line symbol.qtpl:33
	case 2:
		//line symbol.qtpl:33
		qw422016.N().S(`private`)
	//line symbol.qtpl:35
	default:
		//line symbol.qtpl:36
	}
//line symbol.qtpl:37
}

//line symbol.qtpl:37
func WriteGetHumanAccess(qq422016 qtio422016.Writer, value int) {
	//line symbol.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line symbol.qtpl:37
	StreamGetHumanAccess(qw422016, value)
	//line symbol.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line symbol.qtpl:37
}

//line symbol.qtpl:37
func GetHumanAccess(value int) string {
	//line symbol.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
	//line symbol.qtpl:37
	WriteGetHumanAccess(qb422016, value)
	//line symbol.qtpl:37
	qs422016 := string(qb422016.B)
	//line symbol.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
	//line symbol.qtpl:37
	return qs422016
//line symbol.qtpl:37
}

//line symbol.qtpl:41
func StreamGetHumanKind(qw422016 *qt422016.Writer, kind string) {
	//line symbol.qtpl:42
	if kind == "ParmVar" {
		//line symbol.qtpl:42
		qw422016.N().S(`function parameter`)
		//line symbol.qtpl:44
	} else if kind == "Var" {
		//line symbol.qtpl:44
		qw422016.N().S(`variable`)
		//line symbol.qtpl:46
	} else if kind == "CXXRecord" {
		//line symbol.qtpl:46
		qw422016.N().S(`struct or class`)
		//line symbol.qtpl:48
	} else if kind == "CXXMethod" {
		//line symbol.qtpl:48
		qw422016.N().S(`method`)
		//line symbol.qtpl:50
	} else if kind == "EnumConstant" {
		//line symbol.qtpl:50
		qw422016.N().S(`enum value`)
		//line symbol.qtpl:52
	} else {
		//line symbol.qtpl:53
		qw422016.E().S(strings.ToLower(kind))
		//line symbol.qtpl:54
	}
//line symbol.qtpl:55
}

//line symbol.qtpl:55
func WriteGetHumanKind(qq422016 qtio422016.Writer, kind string) {
	//line symbol.qtpl:55
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line symbol.qtpl:55
	StreamGetHumanKind(qw422016, kind)
	//line symbol.qtpl:55
	qt422016.ReleaseWriter(qw422016)
//line symbol.qtpl:55
}

//line symbol.qtpl:55
func GetHumanKind(kind string) string {
	//line symbol.qtpl:55
	qb422016 := qt422016.AcquireByteBuffer()
	//line symbol.qtpl:55
	WriteGetHumanKind(qb422016, kind)
	//line symbol.qtpl:55
	qs422016 := string(qb422016.B)
	//line symbol.qtpl:55
	qt422016.ReleaseByteBuffer(qb422016)
	//line symbol.qtpl:55
	return qs422016
//line symbol.qtpl:55
}

//line symbol.qtpl:59
func (page *SymbolPage) StreamAddProvider(qw422016 *qt422016.Writer, provider *structs.SymbolProvider) {
	//line symbol.qtpl:59
	qw422016.N().S(`
  <a href="`)
	//line symbol.qtpl:60
	qw422016.E().S(provider.Href)
	//line symbol.qtpl:60
	qw422016.N().S(`">`)
	//line symbol.qtpl:60
	qw422016.E().S(provider.Location)
	//line symbol.qtpl:60
	qw422016.N().S(`</a>: `)
	//line symbol.qtpl:60
	qw422016.E().S(provider.Snippet)
	//line symbol.qtpl:60
	qw422016.N().S(`
`)
//line symbol.qtpl:61
}

//line symbol.qtpl:61
func (page *SymbolPage) WriteAddProvider(qq422016 qtio422016.Writer, provider *structs.SymbolProvider) {
	//line symbol.qtpl:61
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line symbol.qtpl:61
	page.StreamAddProvider(qw422016, provider)
	//line symbol.qtpl:61
	qt422016.ReleaseWriter(qw422016)
//line symbol.qtpl:61
}

//line symbol.qtpl:61
func (page *SymbolPage) AddProvider(provider *structs.SymbolProvider) string {
	//line symbol.qtpl:61
	qb422016 := qt422016.AcquireByteBuffer()
	//line symbol.qtpl:61
	page.WriteAddProvider(qb422016, provider)
	//line symbol.qtpl:61
	qs422016 := string(qb422016.B)
	//line symbol.qtpl:61
	qt422016.ReleaseByteBuffer(qb422016)
	//line symbol.qtpl:61
	return qs422016
//line symbol.qtpl:61
}

//line symbol.qtpl:64
func (page *SymbolPage) StreamGetBody(qw422016 *qt422016.Writer) {
	//line symbol.qtpl:64
	qw422016.N().S(` <h1>Symbol: `)
	//line symbol.qtpl:65
	qw422016.E().S(page.Symbol.Name)
	//line symbol.qtpl:65
	qw422016.N().S(`</h1> <ul> `)
	//line symbol.qtpl:68
	for count, kindlinkage := range page.Symbol.Kinds {
		//line symbol.qtpl:68
		qw422016.N().S(` <h2 id="SL`)
		//line symbol.qtpl:69
		qw422016.N().D(count)
		//line symbol.qtpl:69
		qw422016.N().S(`">`)
		//line symbol.qtpl:69
		StreamGetHumanKind(qw422016, kindlinkage.Kind)
		//line symbol.qtpl:69
		qw422016.N().S(` `)
		//line symbol.qtpl:69
		StreamGetHumanAccess(qw422016, kindlinkage.Access)
		//line symbol.qtpl:69
		qw422016.N().S(` `)
		//line symbol.qtpl:69
		StreamGetHumanLinkage(qw422016, kindlinkage.Linkage)
		//line symbol.qtpl:69
		qw422016.N().S(`</h2> `)
		//line symbol.qtpl:71
		if len(kindlinkage.Decls) > 0 {
			//line symbol.qtpl:71
			qw422016.N().S(` <h3>Declared as a prototype...</h3> <ul> `)
			//line symbol.qtpl:74
			for _, provider := range kindlinkage.Decls {
				//line symbol.qtpl:74
				qw422016.N().S(` <li>`)
				//line symbol.qtpl:75
				page.StreamAddProvider(qw422016, &provider)
				//line symbol.qtpl:75
				qw422016.N().S(`</li> `)
				//line symbol.qtpl:76
			}
			//line symbol.qtpl:76
			qw422016.N().S(` </ul> `)
			//line symbol.qtpl:78
		}
		//line symbol.qtpl:78
		qw422016.N().S(` `)
		//line symbol.qtpl:79
		if len(kindlinkage.Defs) > 0 {
			//line symbol.qtpl:79
			qw422016.N().S(` <h3>Defined...</h3> <ul> `)
			//line symbol.qtpl:82
			for _, provider := range kindlinkage.Defs {
				//line symbol.qtpl:82
				qw422016.N().S(` <li>`)
				//line symbol.qtpl:83
				page.StreamAddProvider(qw422016, &provider)
				//line symbol.qtpl:83
				qw422016.N().S(`</li> `)
				//line symbol.qtpl:84
			}
			//line symbol.qtpl:84
			qw422016.N().S(` </ul> `)
			//line symbol.qtpl:86
		}
		//line symbol.qtpl:86
		qw422016.N().S(` `)
		//line symbol.qtpl:87
	}
	//line symbol.qtpl:87
	qw422016.N().S(` </ul> `)
//line symbol.qtpl:89
}

//line symbol.qtpl:89
func (page *SymbolPage) WriteGetBody(qq422016 qtio422016.Writer) {
	//line symbol.qtpl:89
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line symbol.qtpl:89
	page.StreamGetBody(qw422016)
	//line symbol.qtpl:89
	qt422016.ReleaseWriter(qw422016)
//line symbol.qtpl:89
}

//line symbol.qtpl:89
func (page *SymbolPage) GetBody() string {
	//line symbol.qtpl:89
	qb422016 := qt422016.AcquireByteBuffer()
	//line symbol.qtpl:89
	page.WriteGetBody(qb422016)
	//line symbol.qtpl:89
	qs422016 := string(qb422016.B)
	//line symbol.qtpl:89
	qt422016.ReleaseByteBuffer(qb422016)
	//line symbol.qtpl:89
	return qs422016
//line symbol.qtpl:89
}

//line symbol.qtpl:93
func (page *SymbolPage) StreamGetTitle(qw422016 *qt422016.Writer) {
	//line symbol.qtpl:94
	page.BasePage.StreamGetTitle(qw422016)
	//line symbol.qtpl:94
	qw422016.N().S(`symbol:`)
	//line symbol.qtpl:94
	qw422016.N().S(` `)
	//line symbol.qtpl:94
	qw422016.E().S(page.Symbol.Name)
//line symbol.qtpl:95
}

//line symbol.qtpl:95
func (page *SymbolPage) WriteGetTitle(qq422016 qtio422016.Writer) {
	//line symbol.qtpl:95
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line symbol.qtpl:95
	page.StreamGetTitle(qw422016)
	//line symbol.qtpl:95
	qt422016.ReleaseWriter(qw422016)
//line symbol.qtpl:95
}

//line symbol.qtpl:95
func (page *SymbolPage) GetTitle() string {
	//line symbol.qtpl:95
	qb422016 := qt422016.AcquireByteBuffer()
	//line symbol.qtpl:95
	page.WriteGetTitle(qb422016)
	//line symbol.qtpl:95
	qs422016 := string(qb422016.B)
	//line symbol.qtpl:95
	qt422016.ReleaseByteBuffer(qb422016)
	//line symbol.qtpl:95
	return qs422016
//line symbol.qtpl:95
}
